#ifndef FACEBOOK_NETWOK_CLIENT_DEF_H
#define FACEBOOK_NETWOK_CLIENT_DEF_H

#define APPLICATION_ID "210122692339888"
#define FACEBOOK_API_URL "https://graph.facebook.com/"

typedef enum 
{
   FACEBOOK_REQUEST_NO = 0,
   FACEBOOK_REQUEST_TOKEN_DATA,
   FACEBOOK_REQUEST_MYFRIENDS_DATA,
   FACEBOOK_REQUEST_FRIEND_DATA,
   FACEBOOK_REQUEST_GROUPS_DATA,
   FACEBOOK_REQUEST_GROUP_DETAILS
} FACEBOOK_REQUEST_T;

typedef enum 
{
   NETWORKMANAGER_STATE_INIT,
	NETWORKMANAGER_STATE_AUTHORIZE

} FACEBOOK_NETWORKMANAGER_STATE_T;

#endif
